# Workflow to ensure whenever a push is made to master/main branch,
# then pytest and flake8 run automatically.
name: Pytest and Flake8

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.16

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest -v

      - name: Run flake8
        run: flake8 .

      - name: Run Server
        run: uvicorn main:app &
